spring:
  profiles:
    active: local
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://drona.db.elephantsql.com/flkrewxq
    username: flkrewxq
    password: asdasdasd
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 3000

  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus,metrics'
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true