spring:
  datasource:
    url: jdbc:postgresql://drona.db.elephantsql.com/flkrewxq
    username: flkrewxq
    password: 1PSFouUubB85Xf6beNhqbCNabF0k3OKw

  jpa:
    properties:
      hibernate:
        show_sql: true