data:
  file:
    path: bd.json

spring:
  datasource:
    url: jdbc:postgresql://drona.db.elephantsql.com/flkrewxq
    username: flkrewxq
    password: 1PSFouUubB85Xf6beNhqbCNabF0k3OKw
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true