spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus,metrics'
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true